### ISSUE TITLE
Explorer not displaying Blacklist operations

### ISSUE THREAD

**Issue by iamredbar** [oxarbitrage/open-explorer#51]
**Describe the bug**
Open explorer does not display Blacklist operations. It will not load transaction history for an account that it sees a blacklist operation.

**To Reproduce**
- View block 35629137. This block has a blacklist operation from account iamredbar1.
- View user ‘iamredbar1’. The explorer will not load transactions.

**Expected behavior**
Display all transactions correctly.

**Screenshots**

![](https://cdn.steemitimages.com/DQmPJ4sBHVnJgtkJkmEXDFaSp5CKyFRrT6vWhXqbz7ckw5i/Screen%20Shot%202019-03-12%20at%2010.03.25%20AM.png)

![IMG_0003](https://user-images.githubusercontent.com/16945982/54547803-7fc28800-4974-11e9-91df-f08893c932b8.png)

**Desktop (please complete the following information):**
 - OS: multiple, iOS, MacOS
 - Browser: Firefox and Safari

**Comment by oxarbitrage** [comment]
thank you for the report, ill take a look as soon as i can and let you know.

**Comment by oxarbitrage** [comment]
I fixed a bug that was not allowing to show all the operations in page 2 of your account: https://open-explorer.io/#/accounts/iamredbar1

This was not due to the whitelist operation but actually in a problem with the VESTING BALANCE WITHDRAW that you actually have in your account in the same page. 

Fixed in this commit https://github.com/oxarbitrage/open-explorer/commit/161603d5d73ae9333fb43f53f3fdbfa66cf6d881

**Comment by iamredbar** [comment]
I was mistaken then, but I am glad you found the issue.

**Comment by oxarbitrage** [comment]
I added text for the whitelist operation, can see it in action currently at page 4 of your account at https://open-explorer.io/#/accounts/iamredbar1 and in https://github.com/oxarbitrage/open-explorer/commit/9a982828eebc46b23176f9a8c01ff643250bf926
